name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  get-metadata:
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ steps.extract-name.outputs.repo-name }}
      branch-name: ${{ steps.extract-branch.outputs.branch-name }}
    steps:
      - name: Extract repository name
        id: extract-name
        run: |
          FULL_REPO_NAME="${{ github.repository }}"
          REPO_NAME=$(echo "$FULL_REPO_NAME" | cut -d'/' -f2)
          echo "repo-name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Extract branch name
        id: extract-branch
        run: |
          BRANCH_NAME=""
          if [[ "${{ github.ref_type }}" == "branch" ]]; then
            BRANCH_NAME="${{ github.ref_name }}"
          else
            BRANCH_NAME="latest"
          fi
          # Replace slashes with dashes for valid Docker tag
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/\//-/g')
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT

  build:
    needs: get-metadata
    uses: joinupdev/cicd-workflows/.github/workflows/docker-build.yml@main
    with:
      image-name: "${{ needs.get-metadata.outputs.repo-name }}"
      image-tag: "${{ needs.get-metadata.outputs.branch-name }}"
    secrets: inherit

  deploy:
    needs: [build]
    uses: joinupdev/cicd-workflows/.github/workflows/deploy.yml@main
    secrets:
      WATCHTOWER_TOKEN: ${{ secrets.WATCHTOWER_TOKEN }}
